// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Edge struct {
	_tab flatbuffers.Struct
}

func (rcv *Edge) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Edge) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Edge) StartNodeID() int64 {
	return rcv._tab.GetInt64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Edge) MutateStartNodeID(n int64) bool {
	return rcv._tab.MutateInt64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *Edge) EndNodeID() int64 {
	return rcv._tab.GetInt64(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *Edge) MutateEndNodeID(n int64) bool {
	return rcv._tab.MutateInt64(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func CreateEdge(builder *flatbuffers.Builder, StartNodeID int64, EndNodeID int64) flatbuffers.UOffsetT {
	builder.Prep(8, 16)
	builder.PrependInt64(EndNodeID)
	builder.PrependInt64(StartNodeID)
	return builder.Offset()
}
