// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LoginResult struct {
	_tab flatbuffers.Table
}

func GetRootAsLoginResult(buf []byte, offset flatbuffers.UOffsetT) *LoginResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LoginResult{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *LoginResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LoginResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LoginResult) Id() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LoginResult) MutateId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func LoginResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LoginResultAddId(builder *flatbuffers.Builder, Id int64) {
	builder.PrependInt64Slot(0, Id, 0)
}
func LoginResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
