// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Vector struct {
	_tab flatbuffers.Struct
}

func (rcv *Vector) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Vector) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Vector) X() float64 {
	return rcv._tab.GetFloat64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Vector) MutateX(n float64) bool {
	return rcv._tab.MutateFloat64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *Vector) Y() float64 {
	return rcv._tab.GetFloat64(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *Vector) MutateY(n float64) bool {
	return rcv._tab.MutateFloat64(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func CreateVector(builder *flatbuffers.Builder, X float64, Y float64) flatbuffers.UOffsetT {
	builder.Prep(8, 16)
	builder.PrependFloat64(Y)
	builder.PrependFloat64(X)
	return builder.Offset()
}
