// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SignInRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSignInRequest(buf []byte, offset flatbuffers.UOffsetT) *SignInRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SignInRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SignInRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SignInRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SignInRequest) Id() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SignInRequest) MutateId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func SignInRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SignInRequestAddId(builder *flatbuffers.Builder, id int64) {
	builder.PrependInt64Slot(0, id, 0)
}
func SignInRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
