// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ACTOR_FBS_H_
#define FLATBUFFERS_GENERATED_ACTOR_FBS_H_

#include "flatbuffers/flatbuffers.h"

#include "vector_generated.h"

namespace fbs {

struct Actor;

struct Actor FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ID = 4,
    VT_POSITION = 6
  };
  int64_t Id() const {
    return GetField<int64_t>(VT_ID, 0);
  }
  const Vector *Position() const {
    return GetStruct<const Vector *>(VT_POSITION);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_ID) &&
           VerifyField<Vector>(verifier, VT_POSITION) &&
           verifier.EndTable();
  }
};

struct ActorBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_Id(int64_t Id) {
    fbb_.AddElement<int64_t>(Actor::VT_ID, Id, 0);
  }
  void add_Position(const Vector *Position) {
    fbb_.AddStruct(Actor::VT_POSITION, Position);
  }
  explicit ActorBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ActorBuilder &operator=(const ActorBuilder &);
  flatbuffers::Offset<Actor> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Actor>(end);
    return o;
  }
};

inline flatbuffers::Offset<Actor> CreateActor(
    flatbuffers::FlatBufferBuilder &_fbb,
    int64_t Id = 0,
    const Vector *Position = 0) {
  ActorBuilder builder_(_fbb);
  builder_.add_Id(Id);
  builder_.add_Position(Position);
  return builder_.Finish();
}

inline const fbs::Actor *GetActor(const void *buf) {
  return flatbuffers::GetRoot<fbs::Actor>(buf);
}

inline const fbs::Actor *GetSizePrefixedActor(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<fbs::Actor>(buf);
}

inline bool VerifyActorBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fbs::Actor>(nullptr);
}

inline bool VerifySizePrefixedActorBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fbs::Actor>(nullptr);
}

inline void FinishActorBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<fbs::Actor> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedActorBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<fbs::Actor> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_ACTOR_FBS_H_
