// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MOVEREQ_FBS_H_
#define FLATBUFFERS_GENERATED_MOVEREQ_FBS_H_

#include "flatbuffers/flatbuffers.h"

#include "Vector_generated.h"

namespace fbs {

struct MoveReq;
struct MoveReqBuilder;

struct MoveReq FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MoveReqBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_POS = 6
  };
  int64_t ID() const {
    return GetField<int64_t>(VT_ID, 0);
  }
  const fbs::Vector *Pos() const {
    return GetStruct<const fbs::Vector *>(VT_POS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_ID) &&
           VerifyField<fbs::Vector>(verifier, VT_POS) &&
           verifier.EndTable();
  }
};

struct MoveReqBuilder {
  typedef MoveReq Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_ID(int64_t ID) {
    fbb_.AddElement<int64_t>(MoveReq::VT_ID, ID, 0);
  }
  void add_Pos(const fbs::Vector *Pos) {
    fbb_.AddStruct(MoveReq::VT_POS, Pos);
  }
  explicit MoveReqBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  MoveReqBuilder &operator=(const MoveReqBuilder &);
  flatbuffers::Offset<MoveReq> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MoveReq>(end);
    return o;
  }
};

inline flatbuffers::Offset<MoveReq> CreateMoveReq(
    flatbuffers::FlatBufferBuilder &_fbb,
    int64_t ID = 0,
    const fbs::Vector *Pos = 0) {
  MoveReqBuilder builder_(_fbb);
  builder_.add_ID(ID);
  builder_.add_Pos(Pos);
  return builder_.Finish();
}

inline const fbs::MoveReq *GetMoveReq(const void *buf) {
  return flatbuffers::GetRoot<fbs::MoveReq>(buf);
}

inline const fbs::MoveReq *GetSizePrefixedMoveReq(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<fbs::MoveReq>(buf);
}

inline bool VerifyMoveReqBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fbs::MoveReq>(nullptr);
}

inline bool VerifySizePrefixedMoveReqBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fbs::MoveReq>(nullptr);
}

inline void FinishMoveReqBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<fbs::MoveReq> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMoveReqBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<fbs::MoveReq> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_MOVEREQ_FBS_H_
