// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MSGMOVEPUSH_FBS_H_
#define FLATBUFFERS_GENERATED_MSGMOVEPUSH_FBS_H_

#include "flatbuffers/flatbuffers.h"

#include "MsgVector_generated.h"

namespace fbs {

struct MsgMovePush;
struct MsgMovePushBuilder;

struct MsgMovePush FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MsgMovePushBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_POS = 6
  };
  int64_t ID() const {
    return GetField<int64_t>(VT_ID, 0);
  }
  const fbs::MsgVector *Pos() const {
    return GetStruct<const fbs::MsgVector *>(VT_POS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_ID) &&
           VerifyField<fbs::MsgVector>(verifier, VT_POS) &&
           verifier.EndTable();
  }
};

struct MsgMovePushBuilder {
  typedef MsgMovePush Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_ID(int64_t ID) {
    fbb_.AddElement<int64_t>(MsgMovePush::VT_ID, ID, 0);
  }
  void add_Pos(const fbs::MsgVector *Pos) {
    fbb_.AddStruct(MsgMovePush::VT_POS, Pos);
  }
  explicit MsgMovePushBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  MsgMovePushBuilder &operator=(const MsgMovePushBuilder &);
  flatbuffers::Offset<MsgMovePush> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MsgMovePush>(end);
    return o;
  }
};

inline flatbuffers::Offset<MsgMovePush> CreateMsgMovePush(
    flatbuffers::FlatBufferBuilder &_fbb,
    int64_t ID = 0,
    const fbs::MsgVector *Pos = 0) {
  MsgMovePushBuilder builder_(_fbb);
  builder_.add_ID(ID);
  builder_.add_Pos(Pos);
  return builder_.Finish();
}

inline const fbs::MsgMovePush *GetMsgMovePush(const void *buf) {
  return flatbuffers::GetRoot<fbs::MsgMovePush>(buf);
}

inline const fbs::MsgMovePush *GetSizePrefixedMsgMovePush(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<fbs::MsgMovePush>(buf);
}

inline bool VerifyMsgMovePushBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fbs::MsgMovePush>(nullptr);
}

inline bool VerifySizePrefixedMsgMovePushBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fbs::MsgMovePush>(nullptr);
}

inline void FinishMsgMovePushBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<fbs::MsgMovePush> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMsgMovePushBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<fbs::MsgMovePush> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_MSGMOVEPUSH_FBS_H_
