// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_VECTOR_FBS_H_
#define FLATBUFFERS_GENERATED_VECTOR_FBS_H_

#include "flatbuffers/flatbuffers.h"

namespace fbs {

struct Vector;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector FLATBUFFERS_FINAL_CLASS {
 private:
  float X_;
  float Y_;

 public:
  Vector() {
    memset(static_cast<void *>(this), 0, sizeof(Vector));
  }
  Vector(float _X, float _Y)
      : X_(flatbuffers::EndianScalar(_X)),
        Y_(flatbuffers::EndianScalar(_Y)) {
  }
  float X() const {
    return flatbuffers::EndianScalar(X_);
  }
  float Y() const {
    return flatbuffers::EndianScalar(Y_);
  }
};
FLATBUFFERS_STRUCT_END(Vector, 8);

}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_VECTOR_FBS_H_
