[package]
name = "bevy_prototype_lyon"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15.3"
bevy_prototype_lyon = { git = "https://github.com/Nilirad/bevy_prototype_lyon.git", branch = "master" }
