// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MOVEPUSH_FBS_H_
#define FLATBUFFERS_GENERATED_MOVEPUSH_FBS_H_

#include "flatbuffers/flatbuffers.h"

#include "MsgVector_generated.h"

namespace fbs {

struct MovePush;
struct MovePushBuilder;

struct MovePush FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MovePushBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_POS = 6
  };
  int64_t ID() const {
    return GetField<int64_t>(VT_ID, 0);
  }
  const fbs::MsgVector *Pos() const {
    return GetStruct<const fbs::MsgVector *>(VT_POS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_ID) &&
           VerifyField<fbs::MsgVector>(verifier, VT_POS) &&
           verifier.EndTable();
  }
};

struct MovePushBuilder {
  typedef MovePush Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_ID(int64_t ID) {
    fbb_.AddElement<int64_t>(MovePush::VT_ID, ID, 0);
  }
  void add_Pos(const fbs::MsgVector *Pos) {
    fbb_.AddStruct(MovePush::VT_POS, Pos);
  }
  explicit MovePushBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  MovePushBuilder &operator=(const MovePushBuilder &);
  flatbuffers::Offset<MovePush> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MovePush>(end);
    return o;
  }
};

inline flatbuffers::Offset<MovePush> CreateMovePush(
    flatbuffers::FlatBufferBuilder &_fbb,
    int64_t ID = 0,
    const fbs::MsgVector *Pos = 0) {
  MovePushBuilder builder_(_fbb);
  builder_.add_ID(ID);
  builder_.add_Pos(Pos);
  return builder_.Finish();
}

inline const fbs::MovePush *GetMovePush(const void *buf) {
  return flatbuffers::GetRoot<fbs::MovePush>(buf);
}

inline const fbs::MovePush *GetSizePrefixedMovePush(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<fbs::MovePush>(buf);
}

inline bool VerifyMovePushBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fbs::MovePush>(nullptr);
}

inline bool VerifySizePrefixedMovePushBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fbs::MovePush>(nullptr);
}

inline void FinishMovePushBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<fbs::MovePush> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMovePushBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<fbs::MovePush> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_MOVEPUSH_FBS_H_
