// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MSGACTOR_FBS_H_
#define FLATBUFFERS_GENERATED_MSGACTOR_FBS_H_

#include "flatbuffers/flatbuffers.h"

#include "MsgVector_generated.h"

namespace fbs {

struct MsgActor;
struct MsgActorBuilder;

struct MsgActor FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MsgActorBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_POS = 6
  };
  int64_t ID() const {
    return GetField<int64_t>(VT_ID, 0);
  }
  const fbs::MsgVector *Pos() const {
    return GetStruct<const fbs::MsgVector *>(VT_POS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_ID) &&
           VerifyField<fbs::MsgVector>(verifier, VT_POS) &&
           verifier.EndTable();
  }
};

struct MsgActorBuilder {
  typedef MsgActor Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_ID(int64_t ID) {
    fbb_.AddElement<int64_t>(MsgActor::VT_ID, ID, 0);
  }
  void add_Pos(const fbs::MsgVector *Pos) {
    fbb_.AddStruct(MsgActor::VT_POS, Pos);
  }
  explicit MsgActorBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  MsgActorBuilder &operator=(const MsgActorBuilder &);
  flatbuffers::Offset<MsgActor> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MsgActor>(end);
    return o;
  }
};

inline flatbuffers::Offset<MsgActor> CreateMsgActor(
    flatbuffers::FlatBufferBuilder &_fbb,
    int64_t ID = 0,
    const fbs::MsgVector *Pos = 0) {
  MsgActorBuilder builder_(_fbb);
  builder_.add_ID(ID);
  builder_.add_Pos(Pos);
  return builder_.Finish();
}

inline const fbs::MsgActor *GetMsgActor(const void *buf) {
  return flatbuffers::GetRoot<fbs::MsgActor>(buf);
}

inline const fbs::MsgActor *GetSizePrefixedMsgActor(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<fbs::MsgActor>(buf);
}

inline bool VerifyMsgActorBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fbs::MsgActor>(nullptr);
}

inline bool VerifySizePrefixedMsgActorBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fbs::MsgActor>(nullptr);
}

inline void FinishMsgActorBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<fbs::MsgActor> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMsgActorBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<fbs::MsgActor> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_MSGACTOR_FBS_H_
