// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MSGLOGINREQ_FBS_H_
#define FLATBUFFERS_GENERATED_MSGLOGINREQ_FBS_H_

#include "flatbuffers/flatbuffers.h"

namespace fbs {

struct MsgLoginReq;
struct MsgLoginReqBuilder;

struct MsgLoginReq FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MsgLoginReqBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4
  };
  int64_t ID() const {
    return GetField<int64_t>(VT_ID, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_ID) &&
           verifier.EndTable();
  }
};

struct MsgLoginReqBuilder {
  typedef MsgLoginReq Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_ID(int64_t ID) {
    fbb_.AddElement<int64_t>(MsgLoginReq::VT_ID, ID, 0);
  }
  explicit MsgLoginReqBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  MsgLoginReqBuilder &operator=(const MsgLoginReqBuilder &);
  flatbuffers::Offset<MsgLoginReq> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MsgLoginReq>(end);
    return o;
  }
};

inline flatbuffers::Offset<MsgLoginReq> CreateMsgLoginReq(
    flatbuffers::FlatBufferBuilder &_fbb,
    int64_t ID = 0) {
  MsgLoginReqBuilder builder_(_fbb);
  builder_.add_ID(ID);
  return builder_.Finish();
}

inline const fbs::MsgLoginReq *GetMsgLoginReq(const void *buf) {
  return flatbuffers::GetRoot<fbs::MsgLoginReq>(buf);
}

inline const fbs::MsgLoginReq *GetSizePrefixedMsgLoginReq(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<fbs::MsgLoginReq>(buf);
}

inline bool VerifyMsgLoginReqBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fbs::MsgLoginReq>(nullptr);
}

inline bool VerifySizePrefixedMsgLoginReqBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fbs::MsgLoginReq>(nullptr);
}

inline void FinishMsgLoginReqBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<fbs::MsgLoginReq> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMsgLoginReqBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<fbs::MsgLoginReq> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_MSGLOGINREQ_FBS_H_
