// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package message

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ActorMove struct {
	_tab flatbuffers.Table
}

func GetRootAsActorMove(buf []byte, offset flatbuffers.UOffsetT) *ActorMove {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ActorMove{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ActorMove) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ActorMove) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ActorMove) Position(obj *Vector) *Vector {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Vector)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ActorMoveStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ActorMoveAddPosition(builder *flatbuffers.Builder, Position flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(Position), 0)
}
func ActorMoveEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
