// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LoginResult struct {
	_tab flatbuffers.Struct
}

func (rcv *LoginResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LoginResult) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *LoginResult) Id() int64 {
	return rcv._tab.GetInt64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *LoginResult) MutateId(n int64) bool {
	return rcv._tab.MutateInt64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func CreateLoginResult(builder *flatbuffers.Builder, Id int64) flatbuffers.UOffsetT {
	builder.Prep(8, 8)
	builder.PrependInt64(Id)
	return builder.Offset()
}
