name: Benchmark

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
         go-version: '1.13'
    - run: go version
    - name: Install dependencies
      run: sudo apt update && sudo apt install libc6-dev libglu1-mesa-dev libgl1-mesa-dev libxrandr-dev libxcursor-dev libxinerama-dev libxi-dev libasound2-dev
    - run: go get -u go.bobheadxi.dev/gobenchdata
    - name: Run banchmark
      run: make benchmark
