name: Benchmark

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
         go-version: '1.13'
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install libc6-dev libglu1-mesa-dev libgl1-mesa-dev libxrandr-dev libxcursor-dev libxinerama-dev libxi-dev libasound2-dev
        go get -u go.bobheadxi.dev/gobenchdata
    - name: Benchmark
      run: |
        go test -bench . -benchmem ./... > docs/benchmark/benchmarks.log
        cat docs/benchmark/benchmarks.log | /home/runner/go/bin/gobenchdata --append --flat --json docs/benchmark/benchmarks.json -v "${GITHUB_SHA}" -t "ref=${GITHUB_REF}"
    - name: Commit
      run: |
        git config --local user.email "jaewan.huey.park@gmail.com"
        git config --local user.name "Jaewan Park"
        git add docs/benchmark/benchmarks.json
        git commit -m "Update benchmark"
    - name: Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
