name: Benchmark

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run banchmark
      run: make benchmark
