name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Required to create a GitHub release (https://docs.github.com/en/rest/releases/releases#create-a-release).
      contents: write
    env:
      ITCH_TARGET: hueypark/snake-v2
      JORNET_LEADERBOARD_ID: ${{ secrets.JORNET_LEADERBOARD_ID }}
      JORNET_LEADERBOARD_KEY: ${{ secrets.JORNET_LEADERBOARD_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version
        run: |
          echo "CARGO_PKG_VERSION=v$(cargo pkgid | cut -d# -f2 | cut -d: -f2)" >> $GITHUB_ENV

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.10.2

      - name: Install wasm related tools
        run: cargo binstall --no-confirm trunk wasm-bindgen-cli wasm-opt

      - name: Build
        run: trunk build --release --dist .build

      - name: Package
        run: zip --recurse-paths ${{ env.CARGO_PKG_VERSION }}.zip .build

      - name: Upload package to Github release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.CARGO_PKG_VERSION }}.zip
          asset_name: ${{ env.CARGO_PKG_VERSION }}.zip
          release_name: ${{ env.CARGO_PKG_VERSION }}
          tag: ${{ env.CARGO_PKG_VERSION }}
          overwrite: true

      - name: Install butler
        run: |
          curl -L -o butler.zip 'https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default'
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Upload package to Itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
        run: | 
          ./butler push \
            --userversion='${{ env.CARGO_PKG_VERSION }}' \
            ${{ env.CARGO_PKG_VERSION }}.zip \
            ${{ env.ITCH_TARGET }}:web
